# Generated by Django 5.2 on 2025-05-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('expiring_date', models.DateField()),
                ('security_code', models.CharField(max_length=4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_due_date', models.DateField()),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            bases=('cards.card',),
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            bases=('cards.card',),
        ),
    ]
