# Generated by Django 5.2 on 2025-05-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_phonenumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tel2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(help_text='E.g., SP, RJ, MG', max_length=2),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
